define(["commSrc/comm"], function () {
	comm.langConfig["myHsCard"] = {
			12705:'证件已被使用',
			160456:'邮箱已验证通过',
			22000:'操作成功', 
			22000:'操作成功',
			12009:'超出互生币支付限额',
			22004 : "token令牌无效",
			22006 : "客户号不能为空",
			22007 : "登录token不能为空",
			22011:'查询结束时间不能为空',
			22012:'查询开始时间格式错误',
			22013:'查询结束时间格式错误',
			22014:'查询开始时间不能大于查询结束时间',
			22035:'查询开始时间不能为空',
			22043 : "银行卡号不能为空",
			22045 : "银行编号不能为空",
			22046 : "银行卡号码错误",
			22040:  "客户名称不能为空,请先实名注册",
			22047:'申请编号不能为空',
			22048 : "开户行代码不能为空",
			22049 : "开户行名称不能为空",
			30004 : "客户名不能为空",
			160102:"用户信息不存在",
			160359:"登录密码错误",
			160351:"手机短信发送失败",
			160140 : "手机号码不正确",
		    160355:"参数不能为空",
			30026 :"登录密码不能为空",
			22003 :"参数错误 ",
			22021 :"随机令牌不能为空",
			22008 :"randomToken不能为空",
			23901 :"参数错误，请重试",
			30130 :"真实姓名不能为空",
			30131 :"证件类型不能为空",
			30132 :"证件号码不能为空",
			30133 :"国籍不能为空",
			30134 :"身份证号码无效",
			30135 :"证件号码无效",
			30136 :"输入的姓名长度错误",
			30137 : "银行卡绑定已达到最大数量",
			30110 : "请输入银行卡号",
			30138 : "请输入正确的银行卡号",
			30139 : "2次输入的银行卡号不一致，请重试",
			30140 : "开户银行不能为空",
			30141 : "请输入确认银行卡号",
			30142 : "银行名称不能为空",
			30143 : "银行编码不能为空",
			30144 : "开户地区所属国家不能为空",
			30145 : "开户地区所属省份不能为空",
			30146 : "开户地区所属城市不能为空",
			30147 : "是否默认账户不能为空",
			30148 : "确认账户不能为空",
			30149 : "银行卡编码参数错误",
			30150 : "手机号码不能为空",
			30151 : "手机号码错误",
			30152 : "短信验证码不能为空 ",
			30153 : "挂失原因不能为空 ",
			30155 : "企业名称不能为空 ",
			30156 : "注册地址不能为空 ",
			30157 : "企业名称字符数为{0}~{1}",
		    30158 : "企业注册地址字符长度范围为{0}~{1}个",		   
		    30169 : "您尚未进行实名注册，请先注册!",
		    30170 : "公司类型不能为空", 
		    30171 : "性别不能为空",
		    30172 : "发证机关不能为空",
		    30173 : "证件正面照不能为空",
		    30174 : "证件背面照不能为空",
		    30175 : "手持证件照不能为空",
		    30176 : "证件有效期不能为空",
		    30178 : "户籍地址不能为空",
		    30179 : "认证附言长度最大为300个字",
		    30180 : "签发地点不能为空",
		    30181 : "出生地点不能为空",
		    30182 : "成立日期不能为空",
		    30189 : "户籍地址长度应为2-128个字",
		    30190 : "职业长度应为0-50个字符",
		    30191 : "发证机关长度应为2-128个字",
		    30192 : "证件有效期长度应为2-20个字",
		    30193 : "出生地点长度应为2-128个字",
		    30194 : "签发地点长度应为2-40个字",
		    30195 : "签发机关长度应为2-20个字",
		    30196 : "公司类型长度应为2-20个字",
		    30197 : "请输入申请变更原因",
		    30198 : "公司类型长度应为1-200个字",
		    30199 : "您的手机号已经绑定且验证成功，请不需要重复绑定",
		    160129: "您尚未绑定手机号码，为保障您在平台的权益，请尽快完善！",
		    160134: "短信验证码已过期",
		    160133: "短信验证码不正确",
		    160460: "您的邮箱已经绑定且验证成功，请不要重复绑定。",
		    160461: "您的手机号已经绑定且验证成功，请不要重复绑定。",
		    160150: "用户类型非法",
		    160141: "您尚未进行邮箱绑定，为保障您在平台的权益，请尽快完善！点我进行邮箱绑定",
		    160398:"操作失败，银行账号已经存在",
		    160220:"证件已实名注册",
			160354:"邮件发送失败，请检查邮箱地址",
		    12117: "个人提交订单失败",
		    12202:"你已经申请了补办互生卡业务，无需再次申请",
		    sentSuccessfully:"发送成功",
		    addBindEmail:"发送验证邮件成功，请及时登陆邮箱进行验证！",
		    afterRealName:"请完成实名认证后再进行重要信息变更申请。",
		    timeLeft:"剩余时间",
		    getSMSCode:"获取短信验证码",
		    reacquireSMSCode:"重新获取短信验证码",
		    mobileErr : "请输入正确的手机号码",
			dataInvalid:"数据加在错误，请重试",
			relNameSuccessfully : "实名注册成功",
			relNameAuthuccessfully : "提交实名认证申请成功",
			bindBankMaxlength 	: "银行卡号长度范围{0}~{1}位",
			bindBankSuccessfully: "添加银行卡操作成功",
			bindBankConfirmInfo	: "是否确认提交添加银行卡操作?",
			delBankConfirmInfo	: "是否确认删除银行卡操作?",
			delBankSuccessfully : "删除银行卡操作成功",
			bindMobileSuccessfully: "绑定手机号码操作成功",
			editMobileSuccessfully: "修改绑定手机号码操作成功",
			lossCardSuccessfully: "挂失互生卡操作成功",
			solutionLinkedCardSuccessfully: "解除挂失互生卡操作成功",
			randomTokenInvalid:"获取随机报文失败，请重试",
			required1 : "请选择开户银行",
			enterpriseName:"企业名称",
			registeredAddress:"注册地址",
			userName:"真实姓名",
			country:"国籍",
			longTerm:"长期",
			cerValidate : "证件有效期",
			faceImg : '证件正面',
			backImg : '证件反面',
			addrPicImg : '户籍变更证明',
			holdImg : '手持证件大头照',
			addEmailSuccessfully:"验证邮件已经发出，<br>请及时登录邮箱进行验证，完成绑定！",
			importSubmitsuccessfully:"重要信息变更提交成功！提交重要信息变更后，在通过平台审核前，货币转银行账户功能将被禁止！",
			importSubmit:"重要信息变更申请提交处理期间,货币转银行账户业务暂无法受理,确认要提交申请？",
			22052:"验证码错误",
		    22053:"验证码已过期",
		    160137:"邮箱验证码已过期",
		    30166:"两次邮箱信息输入不一致",
		    30167:"邮箱格式不正确",
			//证件类型枚举
			credenceEnum : {
				1:'身份证',
				2:'护照',
				3:'营业执照'
			},
			
			//证件类型枚举
			cardStatusEnum : {
				1:'已启用',
				2:'已挂失'
			},
			
			cardInfoBind : {
				realNameBind : {
					required : "请输入真实姓名",
					maxlength : "姓名最大长度{0}位!",
					minlength : "姓名最小长度{0}位",
					required2 : "确认姓名不能为空",
					equalTo : "两次输入的姓名不一样"
				},
				mobileBind : {
					mobile : "请输入手机号码",
					mobileErr : "请输入正确的手机号码",
					checkCode : "请输入短信验证码",
					digits : "请输入正确的短信验证码",
					maxlength : "验证码不能超过{0}位",
					pwd : "请输入登录密码"
				},
				mailBind : {
					required : "请输入邮箱",
					required1 : "请输入确认邮箱",
					required2 : "请输入登录密码",
					email : "请输入正确的邮箱格式",
					equalTo : "两次邮箱输入不一致"
				}
		},
		realNameReg : {
			nameLength : "请输入2~20字的名字",
			required : "请输入证件号码",
			cernum :  "证件号码格式错误",
			realName: "输入内容含有非法字符"
		},
		realNameAuth : {
			requiredSex : "请选择性别",
			requiredAddress : "请输入户籍地址",
			requiredLicence : "请输入发证机关",
			licenceIssuing:"发证机关长度为2-20个字",
			requiredExpiryDate : "请输入证件有效期",
			requiredJob : "请输入职业",
			job : "请输入正确格式的职业",
			jobRangLength:"职业长度为2-20个字",
			requiredText : "请输入认证附言",
			requiredTop : "请上传证件正面图片",
			requiredBack : "请上传证件反面图片",
			requiredCack : "请上传手持照片图片",
			requiredBlogImage : "请上传户籍变更证明",
			requiredCode : "请输入验证码!",
			rangelength : "请输入正确的验证码",
			remote : "验证码输入错误",
			requiredPlaceOfBirth : "请输入出生地点",
			requiredIssuingAuthority : "请输入签发机关",
			newLicenceIssuingLength : "请输入2~128字发证机关",
			requiredPlaceOfIssue : "请输入签发地点",
			requiredDatOfEstablishment : "请输入成立日期",
			dateFormError : "成立日期格式不正确"
		},
		imporantReg : {
			entNameLength : "请输入2~64字企业名称",
			entRegAddrLength : "请输入2~128字注册地址"
		},
		hsCardLossReg : {
			required : "请输入挂失原因",
			requiredPwd : "请输入登录密码"
		},
		hsCardDisLossReg : {
			
		},
		hsCardReapply : {
			reason : "请输入补办原因",
			address : "请选择补办地址",
			dealPwd : "请输入交易密码",
			digits : "请输入正确的交易密码",
			maxlength : "交易密码的长度为{0}位",
			minlength : "交易密码的长度为{0}位"
		},
		userAddress : {
			receiverNameRequired : "请输入收货人姓名",
			phoneRequired : "请输入收货人手机",
			fixedTelephoneRequired : "请输入收货人电话",
			areaRequired : "请选择收货人地区",
			userAddressRequired : "请输入收货人详细地址",
			postcodeRequired : "请输入收货人邮编",
			mobile : "手机号码格式错误",
			phoneCN : "电话号码格式错误",
			zipCode : "邮编格式错误",
			addAddressSuccess : "添加收货地址成功",
			updateAddressSuccess : "修改收货地址成功",
			maxAddress :"最多添加10条收货地址"
		},
		importantInfoChange : {
			required : "请输入真实姓名",
			equalName : "姓名没有变更",
			equalId : "证件号码没有变更",
			equalJob : "职业没有变更",
			equalAddress : "户籍地址没有变更",
			equalLicence : "发证机关没有变更",
			equalExpiryDate : "证件有效期没有变更",
			cernum : "证件号码格式错误",
			job : "请输入正确的格式",
			requiredReason : "请输入申请变更的原因",
			requiredTop : "请上传证件正面图片",
			requiredBack : "请上传证件反面图片",
			requiredCack : "请上传手持照片图片",
			requiredCode : "请输入验证码!",
			rangelength : "请输入正确的验证码",
			remote : "验证码输入错误"
		},
		bankCardTypeEnum : {//银行卡类型
			1:'储蓄卡',
			2:'信用卡'
		},
		bankSubmitSuccess:'快捷支付卡添加成功',
		confirmDelPayBank:'确定删除此快捷支付卡？',
		12705:"证件已被使用",
		address_length : "详细地址字符最大长度为{0}",
		pleaseSelectQuick:"请先阅读《快捷支付服务协议》并同意",
		importNoChange : "内容没有变更!",
		pleaseSelectProvince:'请选择所在地区省份',
		pleaseSelectCity:'请选择所在地区城市',
		pleaseInputAddr:'请填入详细地址',
		pleaseInputRightProvinceCode:'请输入正确的邮政编码',
		pleaseInputAddr:'请填入详细地址',
		pleaseInputConsigneeName:'请填入收货人姓名',
		pleaseInputMobile:'请填入手机号码',
		pleaseInputRightMobile:'请填入正确手机号码',
		pleaseInputRightTel:'请填入正确电话号码',
		pleaseEnterRealName:' 客户名称不能为空，请先在基本资料填写真实姓名。',
		22069: "业务操作失败,请稍后重试"

	}
});